- name: Build configs from template
  hosts: fabric
  gather_facts: no

  tasks:
    - name: Ensure local configs directory exists
      ansible.builtin.file:
        path: "{{ lookup('env','PWD') }}/configs"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true

    - name: Build from Jinja template locally
      ansible.builtin.template:
        src: ../templates/interfaces.j2
        dest: "{{ lookup('env','PWD') }}/configs/{{ inventory_hostname }}.cfg"
        mode: '0644'
      delegate_to: localhost
